// Структурированный учебный план для немецкого языка по уровням
export type Topic = { title: string; description?: string };
export type Level = 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';

export type CurriculumStage = {
  level: Level;
  grammar: Topic[];
  vocabulary: Topic[];
};

export const germanCurriculum: CurriculumStage[] = [
  {
    level: 'A1',
    grammar: [
      { title: 'Личные местоимения и спряжение глаголов', description: 'ich, du, er/sie, wir, ihr, sie; глаголы sein, haben, kommen.' },
      { title: 'Вопросительные слова и ответы', description: 'wie, woher, wo.' },
      { title: 'Определённые и неопределённые артикли', description: 'der, die, das; ein, eine.' },
      { title: 'Отрицание с kein/e', description: 'Das ist kein Kuli.' },
      { title: 'Притяжательные артикли', description: 'mein, dein.' },
      { title: 'Императив (вежливая форма)', description: 'Kommen Sie, bitte.' },
      { title: 'Глаголы с изменением гласной', description: 'schlafen, waschen.' },
      { title: 'Отделяемые глаголы', description: 'einladen, fernsehen.' },
      { title: 'Порядок слов с временными обстоятельствами', description: 'Am Dienstag geht er zum Friseur.' },
      { title: 'Аккузатив: артикли и местоимения', description: 'den, das, die; mich, dich, ihn.' },
      { title: 'Модальные глаголы', description: 'können, müssen, wollen, dürfen.' },
      { title: 'Прошедшее время (Perfekt) с haben и sein', description: 'Ich habe getanzt; Er ist geflogen.' },
      { title: 'Простое прошедшее время (Präteritum) глаголов sein и haben', description: 'war, hatte.' },
      { title: 'Предлоги места и времени с дативом', description: 'bei, mit, nach, zu.' },
    ],
    vocabulary: [
      { title: 'Приветствия и прощания', description: 'Hallo, Guten Morgen, Tschüss, Auf Wiedersehen' },
      { title: 'Семья', description: 'Mutter, Vater, Bruder, Schwester' },
      { title: 'Числа', description: 'eins, zwei, drei, ...' },
      { title: 'Профессии', description: 'Lehrer, Arzt, Student...' },
      { title: 'Еда и напитки', description: 'Brot, Wasser, Apfel...' },
      { title: 'Погода', description: 'Sonne, Regen, Schnee...' },
      { title: 'Дни недели, месяцы', description: 'Montag, Januar...' },
      { title: 'Город, транспорт', description: 'Bus, Bahnhof, Straße...' },
      { title: 'В доме, квартира, мебель', description: 'Tisch, Stuhl, Zimmer...' },
      { title: 'Покупки, магазины', description: 'Kaufen, Preis, Supermarkt...' },
    ],
  },
  {
    level: 'A2',
    grammar: [
      { title: 'Сравнительная и превосходная степень прилагательных', description: 'besser, am besten.' },
      { title: 'Придаточные предложения с wenn и als', description: 'Wenn er kommt, bekommt er Gummibärchen.' },
      { title: 'Модальные глаголы в Präteritum', description: 'konnte, musste.' },
      { title: 'Демонстративные артикли', description: 'dieser, diese, dieses.' },
      { title: 'Придаточные предложения с bevor', description: 'Ruf bitte an, bevor du gehst.' },
      { title: 'Возвратные глаголы в аккузативе', description: 'sich setzen, sich beeilen.' },
      { title: 'Глаголы с предлогами', description: 'sich ärgern über.' },
      { title: 'Выражение следствия с deshalb', description: 'Deshalb geht sie in die Küche.' },
      { title: 'Вежливые просьбы с Konjunktiv II', description: 'Könntest du mir helfen?' },
      { title: 'Прилагательные после артикля', description: 'der neue Laptop, ein schönes Kleid.' },
      { title: 'Будущее время с Präsens и werden', description: 'Morgen geht er zur Schule; Ich werde Fußballer.' },
      { title: 'Придаточные предложения с damit', description: 'Alle bringen etwas mit, damit wir ein Buffet haben.' },
      { title: 'Относительные предложения в именительном падеже', description: 'Da ist eine Frau, die eine Panne hat.' },
      { title: 'Косвенные вопросы с вопросительным словом и с ob', description: 'Der Lehrer fragt, wann er kommt; Er fragt, ob du kommst.' },
    ],
    vocabulary: [
      { title: 'Путешествия', description: 'Bahnhof, Fahrkarte, abfahren...' },
      { title: 'Праздники', description: 'Geburtstag, Weihnachten...' },
      { title: 'Здоровье', description: 'Arzt, Krankheit, Tablette...' },
      { title: 'Одежда и цвета', description: 'Hose, Hemd, blau, rot...' },
      { title: 'Работа и профессии', description: 'Büro, Kollege, Chef...' },
      { title: 'Письмо, электронная почта', description: 'Brief, E-Mail...' },
      { title: 'Расписание, встречи', description: 'Termin, Uhrzeit...' },
    ],
  },
  {
    level: 'B1',
    grammar: [
      { title: 'Предлоги с чередованием падежей', description: 'in, an, auf.' },
      { title: 'Инфинитив с zu после определённых глаголов', description: 'Vergiss nicht anzurufen.' },
      { title: 'Рефлексивные местоимения', description: 'Ich interessiere mich; Du siehst dir an.' },
      { title: 'Противопоставление с sondern', description: 'Sie hat kein weißes Papier, sondern blaues.' },
      { title: 'Относительные местоимения в аккузативе', description: 'Der Fehler, den er gemacht hat.' },
      { title: 'Генитив', description: 'die Eröffnung des Kontos.' },
      { title: 'Придаточные предложения с obwohl', description: 'Obwohl wir neu sind, fühlen wir uns wohl.' },
      { title: 'Perfekt vs. Präteritum', description: 'расширено: повествование, формальный и неформальный стиль.' },
      { title: 'Plusquamperfekt', description: 'Ich hatte gemacht.' },
      { title: 'Konjunktiv II', description: 'würde, könnte, hätte…' },
      { title: 'Пассив (Präsens и Präteritum)', description: '' },
      { title: 'Наречия времени и порядка', description: 'zuerst, danach, schließlich.' },
      { title: 'Инфинитивные конструкции mit zu', description: '' },
      { title: 'Relativsätze', description: 'который, где…' },
      { title: 'Предлоги с Genitiv', description: 'trotz, während, wegen и др.' },
      { title: 'Временные и причинно-следственные конструкции', description: '' },
      { title: 'Индиректная речь (введение)', description: '' },
    ],
    vocabulary: [
      { title: 'Работа и профессия', description: 'Beruf, Bewerbung, Chef...' },
      { title: 'Образование', description: 'Schule, Universität...' },
      { title: 'Общество и культура', description: 'Kultur, Medien...' },
      { title: 'Природа и экология', description: 'Natur, Umwelt...' },
      { title: 'Истории и события', description: 'Geschichte, Ereignis...' },
      { title: 'Чувства и мнения', description: 'Gefühl, Meinung...' },
    ],
  },
  {
    level: 'B2',
    grammar: [
      { title: 'Конъюнктив II в прошедшем времени с модальными глаголами', description: 'Du hättest gehen sollen.' },
      { title: 'Пассивные конструкции: процессуальный и состояниный пассив', description: 'Die Wand ist gestrichen worden. / Die Wand ist gestrichen.' },
      { title: 'Неразделяемые глаголы', description: 'durchführen, durchlaufen.' },
      { title: 'Словосочетания существительное + глагол', description: 'Einfluss nehmen, Hilfe leisten.' },
      { title: 'Инфинитив с zu', description: 'Ich habe beschlossen, zu gehen.' },
      { title: 'Выражения с es', description: 'Es ist wichtig, pünktlich zu sein.' },
      { title: 'Склонение прилагательных (повторение)', description: 'ein schönes Haus, das schöne Haus.' },
      { title: 'Выражение цели с damit, um zu', description: 'Er lernt, um die Prüfung zu bestehen.' },
      { title: 'Способы действия с indem, ohne zu', description: 'Er lernt, indem er liest; Ohne zu fragen.' },
      { title: 'Причастия I и II как прилагательные', description: 'die bestehende Regel, der geschriebene Text.' },
    ],
    vocabulary: [
      { title: 'Работа и карьера', description: 'Bewerbung, Vorstellungsgespräch, Arbeitsvertrag...' },
      { title: 'Наука и техника', description: 'Technologie, Forschung, Entwicklung...' },
      { title: 'Путешествия и культура', description: 'Kulturreise, Sehenswürdigkeiten...' },
      { title: 'Экономика и финансы', description: 'Wirtschaft, Geld, Bank...' },
      { title: 'Здоровье и спорт', description: 'Fitness, Ernährung, Gesundheit...' },
      { title: 'Межличностные отношения', description: 'Freundschaft, Partnerschaft...' },
    ],
  },
  {
    level: 'C1',
    grammar: [
      { title: 'Сложные синтаксические структуры', description: 'длинные придаточные предложения, косвенная речь.' },
      { title: 'Формальный и научный стиль речи', description: 'использование пассивных конструкций, номинализации.' },
      { title: 'Тонкости употребления модальных глаголов и Konjunktiv II', description: 'выражение предположений, вежливых просьб.' },
      { title: 'Сложные лексические структуры', description: 'идиомы, устойчивые выражения.' },
      { title: 'Аргументация и выражение мнения', description: 'различные способы выражения согласия/несогласия.' },
      { title: 'Стилизация речи', description: 'официальная, неофициальная, научная.' },
    ],
    vocabulary: [
      { title: 'Научная и академическая лексика', description: 'Forschung, Analyse, These...' },
      { title: 'Профессиональная коммуникация', description: 'Verhandlung, Präsentation...' },
      { title: 'Медиа и массмедиа', description: 'Zeitung, Rundfunk, Medien...' },
      { title: 'Политика и общество', description: 'Regierung, Gesellschaft, Wahl...' },
      { title: 'Экология и окружающая среда', description: 'Klimawandel, Umweltschutz...' },
      { title: 'Культура и искусство', description: 'Literatur, Theater, Kunst...' },
    ],
  },
  {
    level: 'C2',
    grammar: [
      { title: 'Совершенное владение сложными синтаксическими структурами', description: 'многоуровневые придаточные, сложные обороты.' },
      { title: 'Тонкости стиля и регистров', description: 'официальный, научный, разговорный стиль.' },
      { title: 'Гибкое использование всех времён и залогов', description: 'Präsens, Präteritum, Perfekt, Plusquamperfekt, Futur I/II, Passiv.' },
      { title: 'Сложные идиоматические выражения', description: 'Sprichwörter, Redewendungen.' },
      { title: 'Аргументация на абстрактные темы', description: 'философия, искусство, политика.' },
      { title: 'Анализ и интерпретация текстов', description: 'литературная критика, эссе.' },
    ],
    vocabulary: [
      { title: 'Абстрактные и философские понятия', description: 'Ethik, Ästhetik, Gerechtigkeit...' },
      { title: 'Высокий уровень профессиональной лексики', description: 'Jura, Medizin, Technik...' },
      { title: 'Литературные и художественные термины', description: 'Metapher, Symbolik...' },
      { title: 'Межкультурная коммуникация', description: 'Interkulturalität, Globalisierung...' },
      { title: 'Современные тенденции', description: 'Digitalisierung, Innovation...' },
      { title: 'Сложные выражения для дебатов и дискуссий', description: 'Meinung äußern, widersprechen...' },
    ],
  },
]; 