
// This file is automatically generated by the Firebase setup.
// Do not edit this file manually, as any changes will be overwritten.
import { FirebaseOptions } from 'firebase/app';

// The following value is placeholder and will be replaced by the
// real configuration when the app is deployed.
export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIza-...",
  authDomain: "project-id.firebaseapp.com",
  projectId: "project-id",
  storageBucket: "project-id.appspot.com",
  messagingSenderId: "...",
  appId: "1:...:web:...",
  measurementId: "G-..."
};
